services:

  stringer-testall-sql:
    container_name: stringer-testall-sql
    build:
      context: ../.
      dockerfile: docker/sql.dockerfile
    image: stringer-testall-sql
    networks:
      - stringer
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  stringer-testall-redis:
    container_name: stringer-testall-redis
    image: redis:8.0.3-alpine
    networks:
      - stringer
    ports:
      - "6379:6379"

  stringer-testall-minio:
    container_name: stringer-testall-minio
    image: minio/minio:RELEASE.2025-07-18T21-56-31Z
    networks:
      - stringer
    environment:
      MINIO_ACCESS_KEY: localtest
      MINIO_SECRET_KEY: localtest
    ports:
      - "9000:9000"
    command: "minio server /data"

networks:
  stringer:
    name: stringer